### ISSUE TITLE
你好，请问你有SynthText上预训练的模型吗？

### ISSUE THREAD

**Issue by whereitogo** [lsr12345/DB#1]
@lsr12345

**Comment by lsr12345** [comment]
需要预训练模型的话可以参考 https://github.com/xuannianz/DifferentiableBinarization这里

**Comment by whereitogo** [comment]
> 需要预训练模型的话可以参考 [https://github.com/xuannianz/DifferentiableBinarization这里](https://github.com/xuannianz/DifferentiableBinarization%E8%BF%99%E9%87%8C)

是这样的，我在用这个模型训练（SynthText）时loss一直卡在4.9xx，（即使直接使用icdar2015或icdar2017）请问你有遇见这个情况吗？
